# Generated by Django 2.2 on 2019-11-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=50)),
                ('book_genre', models.CharField(max_length=30)),
                ('book_writer', models.CharField(max_length=50)),
                ('book_rating', models.IntegerField(max_length=1)),
            ],
        ),
    ]
