# Generated by Django 2.2 on 2019-11-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('student_faculty', models.CharField(max_length=30)),
                ('stuent_shift', models.CharField(max_length=20)),
            ],
        ),
    ]
