# Generated by Django 2.2 on 2019-11-27 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stuent_shift',
            new_name='student_shift',
        ),
    ]
