# Generated by Django 2.2 on 2019-11-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=50)),
                ('movie_genre', models.CharField(max_length=50)),
                ('movie_director', models.CharField(max_length=50)),
                ('movie_rating', models.IntegerField(max_length=1)),
            ],
        ),
    ]
